---
- name: Get docker compose version
  shell: docker compose version
  register: docker_compose_version

- name: Check docker compose
  fail:
    msg: "Docker compose is required"
  when: docker_compose_version.stdout.find("Docker Compose version") == -1

- name: Setup Monitoring [prometheus]
  include_tasks: prometheus.yml

- name: Setup Monitoring [grafana]
  include_tasks: grafana.yml
  when: (service_grafana | bool)

- name: Create monitoring compose
  template:
    src: monitoring-compose.yml.j2
    dest: /usr/local/share/dodasts/monitoring/compose.yml

- name: Run monitoring
  shell:
    cmd: docker compose up -d
    chdir: /usr/local/share/dodasts/monitoring
